### ISSUE TITLE
CI: Use Kustomize instead of Helm with K8S 1.14?

### ISSUE THREAD

**Issue by LouisStAmour** [Azure/kubernetes-hackfest#100]
Though this might require a bit more stability on Kustomize's end for Windows compatibility: https://github.com/kubernetes-sigs/kustomize/issues/834

**Comment by chzbrgr71** [comment]
We love Helm!

**Comment by jschluchter** [comment]
Feel free to create a PR with Kustomize @LouisStAmour. For now, closing.

**Comment by LouisStAmour** [comment]
If anyone finds this later, there's also https://github.com/Microsoft/fabrikate
