### ISSUE TITLE
Securing Tiller: base64 -D not supported in some cases

### ISSUE THREAD

**Issue by swgriffith** [Azure/kubernetes-hackfest#109]
If you try to run the tiller-namespace-setup.sh shell script in the cloud shell, or in some linux distros you'll get the following error:

base64: invalid option -- 'D'

If we assume users are deploying from the cloud shell, then we should change this to -d or --decode to resolve. If we dont make that assumption we should add a note that users should validate their platform support and edit the script accordingly.

**Comment by swgriffith** [comment]
I submitted my PR assuming that our target users are on cloud shell for the whole hackfest.

**Comment by chzbrgr71** [comment]
Stone cold tillah. PR merged
