### ISSUE TITLE
Jenkins lab could use a refresh

### ISSUE THREAD

**Issue by swgriffith** [Azure/kubernetes-hackfest#138]
There are a few changes we need to look at for the Jenkins lab and possibly refresh:
1. Some UI changes have led to a bit of a disconnect between the steps and the user experience
2. The lab assumes Helm 2.x, but cloud shell is starting to upgrade to Helm 3. The build will fail if you havent initialized Tiller and setup RBAC

Probably need to discuss if we assume Helm 3 as the baseline now, and update all the labs accordingly, or if we just add notes to each lab for 2.x vs 3.x

**Comment by swgriffith** [comment]
Addressed by #143

**Comment by jschluchter** [comment]
@swgriffith fixed this in #143
