### ISSUE TITLE
not able to create batch process ACI container

### ISSUE THREAD

**Issue by rathishrms** [Azure/kubernetes-hackfest#168]
team, while trying to build the ACI container image for batch process update to cosmos db i receive the below error. Tried to use the latest sift ("sift": "13.1.10",) version as well, but no luck. Any help is much appreciated.

npm ERR! sift not accessible from mongoose

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-12T12_49_27_888Z-debug.log

**Comment by chzbrgr71** [comment]
![image](https://user-images.githubusercontent.com/10157853/87334268-9f7fa700-c4fb-11ea-8829-f5df53df99df.png)

**Comment by chzbrgr71** [comment]
I made an update to the package-lock.json and it started working for me. Try pulling latest and trying again

**Comment by jschluchter** [comment]
@chzbrgr71 shall we consider this a non-issue and close?

**Comment by chzbrgr71** [comment]
Yes
