### ISSUE TITLE
Jenkins lab need instructions for sp

### ISSUE THREAD

**Issue by chzbrgr71** [Azure/kubernetes-hackfest#17]
We should have the users create a new service principal for use with Jenkins. It would be helpful to provide CLI steps for the create and where to find the 4 values.

**Comment by dstrebel** [comment]
Thinking we may want to just have the user create a SP in the create-aks-cluster lab, so they can use it for any other labs that require it.

**Comment by chzbrgr71** [comment]
I would prefer to have them create a new one since that is a bit more real world from a security perspective (separation of duties)
