### ISSUE TITLE
Add these instructions to the Jenkins Lab

### ISSUE THREAD

**Issue by hackersifu** [Azure/kubernetes-hackfest#18]
These would be for finding the Client and Tenant IDs for entering into Jenkins:

Client (or Application ID) - In the Azure console, search for "Azure Active Directory" and click on it. In the left pane, under Manage, select "App registrations", then click "View all applications" in the right tab. Once done, select your Display Name and double-click. The Application ID will be listed in the pane.

Tenant ID (or Directory ID) - In the Azure CLI, run the following command:

az account show

The Tenant ID will be shown in the field "tenantID".

**Comment by thedude-lebowski** [comment]
we should update this lab to create a separate SP for use with Jenkins.
