### ISSUE TITLE
Lab 1 / Adding variable to .bashrc does'nt point to users home directory

### ISSUE THREAD

**Issue by dazdaz** [Azure/kubernetes-hackfest#27]
Lab 1

echo export UNIQUE_SUFFIX=$UNIQUE_SUFFIX >> .bashrc

Should be the following, to write into .bashrc in the users home directory, not in current directory which is kubernetes-hackfest/labs/create-aks-cluster.

echo export UNIQUE_SUFFIX=$UNIQUE_SUFFIX >> ~/.bashrc

**Comment by dstrebel** [comment]
Added path to home directory
