### ISSUE TITLE
Lab 1 / kubectl cluster-info dump : error: missing apiVersion or kind and cannot assign it; no kind is registered for the type core.NodeList

### ISSUE THREAD

**Issue by dazdaz** [Azure/kubernetes-hackfest#28]
$ kubectl cluster-info dump
error: missing apiVersion or kind and cannot assign it; no kind is registered for the type core.NodeList
$ kubectl version --short
Client Version: v1.11.0
Server Version: v1.10.3

Recommendation : Update docs and deploy Kubernetes version 1.11.2 or 1.11.0.

**Comment by dstrebel** [comment]
We'll look at a better info for troubleshooting section, but don't believe it's needed now in the create cluster lab.
