### ISSUE TITLE
Lab 2 / reg-acr.sh

### ISSUE THREAD

**Issue by dazdaz** [Azure/kubernetes-hackfest#29]
Lab 2

1.Please add in "cd" below at the beginning of Lab 2.   I know this is implied however people will still ask this question.
```
"cd kubernetes-hackfest/labs/build-application"
```

2.I'd suggest changing the variables in reg_acr.sh to the following or updating this script
```
AKS_RESOURCE_GROUP=$RGNAME
AKS_CLUSTER_NAME=$CLUSTERNAME
ACR_RESOURCE_GROUP=$RGNAME
ACR_NAME=$ACRNAME
```

**Comment by dstrebel** [comment]
reg-acr.sh updated to accept env variables
