### ISSUE TITLE
Lab 3 / Step 4 - updating values.yaml to point to newly created ACR

### ISSUE THREAD

**Issue by dazdaz** [Azure/kubernetes-hackfest#31]
Would'nt it be simpler to say, change the ACR configuration within the following files to point to your newly created ACR and update the version number.

It took me a few minutes of looking for these files and re-reading what was being asked, let's make it dead simple.
```
./service-tracker-ui/values.yaml
./data-api/values.yaml
./flights-api/values.yaml
./weather-api/values.yaml
./quakes-api/values.yaml
```

**Comment by dstrebel** [comment]
For you recommendation here are you looking for linking the file locations from this page?

**Comment by dazdaz** [comment]
If we jut add in the exact files to update, it makes it a little easier to understand which files to update, in the instructions.
