### ISSUE TITLE
Lab 4 / URL Update for VSTS

### ISSUE THREAD

**Issue by dazdaz** [Azure/kubernetes-hackfest#34]
The link to creating a VSTS account does'nt work due to the re-branding of VSTS to Azure DevOps so I presume that you want to update it to this one.

https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/create-organization-msa-or-work-student?view=vsts

Old link references in the docs :
https://docs.microsoft.com/en-us/vsts/organizations/accounts/create-account-msa-or-work-student?view=vsts

**Comment by chzbrgr71** [comment]
creating a new lab with Azure DevOps product. This will be fixed.
