### ISSUE TITLE
Need to add resource requests and limits to the Helm charts

### ISSUE THREAD

**Issue by thedude-lebowski** [Azure/kubernetes-hackfest#43]

**Comment by jschluchter** [comment]
![lebowski](https://user-images.githubusercontent.com/492374/45791693-5ee0da80-bc50-11e8-9e51-1a0d15dcf8ff.jpg)

**Comment by chzbrgr71** [comment]
This is fixed with https://github.com/Azure/kubernetes-hackfest/pull/70

**Comment by chzbrgr71** [comment]
done
