### ISSUE TITLE
Upgrade to Kubernetes version to be deployed to 1.11.5

### ISSUE THREAD

**Issue by dazmsft** [Azure/kubernetes-hackfest#68]
Please update Lab 1, so that Kubernetes 1.11.5 is deployed else people will experience the following error.

$ az aks create -n $CLUSTERNAME -g $RGNAME -k 1.11.3 --service-principal $APPID --client-secret $CLIENTSECRET --generate-ssh-keys -l southeastasia --node-count 3 --enable-addons http_application_routing,monitoring
Operation failed with status: 'Bad Request'. Details: The value of parameter orchestratorProfile.OrchestratorVersion is invalid.

**Comment by dstrebel** [comment]
Updated to 1.11.4 as it will allow users to upgrade cluster to 1.11.5 to show how upgrades are done.
