### ISSUE TITLE
Path should be just "/" without UI so that service loads properly.

### ISSUE THREAD

**Issue by GitMetal** [Azure/kubernetes-hackfest#82]
https://github.com/Azure/kubernetes-hackfest/blob/d4839bde3bd5b0c4f8dd2dcdbf5f62012d65b69a/labs/networking/ingress/service-tracker-ingress.yaml#L17

**Comment by GitMetal** [comment]
Network ingress lab had problem where service tracker ui was not loading in browser because of the /ui path

**Comment by chzbrgr71** [comment]
fixed. Thank you!
