### ISSUE TITLE
oh snap, 502 Bad Gateway

### ISSUE THREAD

**Issue by snpdev** [Azure/kubernetes-hackfest#92]
I did the Configure Ingress Controller lab _before_ Configure Network Policy. 

At the "Test out the Application by going to the Dashboard..." step of the Configure Network Policy lab, I immediately get a 502 Bad Gateway error, as my service-tracker-ui  service is now of type ClusterIP, and I access the ui via https://[myacr].eastus.cloudapp.azure.com/ui#/dashboard, not from a LoadBalancer IP address.

Perhaps the README.md should note this distinction?

![image](https://user-images.githubusercontent.com/1825479/51942478-2b277580-23e5-11e9-8923-e1281366c1db.png)

**Comment by chzbrgr71** [comment]
This is expected.

**Comment by snpdev** [comment]
I know it's expected... Just concerned about folks getting confused because it is not mentioned in the lab [README.md](https://github.com/Azure/kubernetes-hackfest/blob/master/labs/networking/network-policy/README.md). I guess this is one of those "let people put 2 & 2 together" issues. No problem.
