### ISSUE TITLE
dial tcp: i/o timeout

### ISSUE THREAD

**Issue by snpdev** [Azure/kubernetes-hackfest#94]
During hackfest in Boston, several users (but not all) experience the following issue. Any thoughts?

```
odl_user@Azure:~/kubernetes-hackfest$ helm upgrade --install data-api ~/kubernetes-hackfest/charts/data-api --namespace hackfest

Error: UPGRADE FAILED: Get https://aksodluser-aks-rg-odluser22-08dbf2-9cd3b3e6.hcp.eastus.azmk8s.io:443/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%!D(MISSING)data-api%!C(MISSING)OWNER%!D(MISSING)TILLER%!C(MISSING)STATUS%!D(MISSING)DEPLOYED: dial tcp: i/o timeout
```
This occurs for all charts.

**Comment by snpdev** [comment]
**Follow-up**: I could not replicate the problem. About 1/4 of the event attendees had this issue. There was some effort to debug, but I could not let us get bogged down. After lunch, attendees who faced the issue partnered with people who successfully deployed the Service Tracker charts, which worked out well.

Ahead of the Friday event in New York, if anyone has debugging suggestions, please chime in.

Note: https://github.com/helm/helm/issues/4171 refers to "a bug in Azure proxy pod," but this is from June 2018. Still relevant, perhaps?

**Comment by chzbrgr71** [comment]
Apparently there were some intermittent issues related to Tiller and some clusters yesterday. I think it is something that can be ignored for now. But be sure your Helm client is up to date just to be safe.

**Comment by marrobi** [comment]
I've hit this today, AKS deployed today and Helm v2.13.1 client and server.

**Comment by alexeyzimarev** [comment]
Same here. Suddenly, all newly deployed pods with Tiller report this issue. All Tiller pods deployed previously, keep working as before.
