### ISSUE TITLE
Prometheus Lab, no kube-dns-v20 deployment

### ISSUE THREAD

**Issue by snpdev** [Azure/kubernetes-hackfest#95]
Step 3 of the Prometheus Lab has the following step:
```
# Edit kube-dns to update Prometheus ENV (Fixes DNS API Metrics)
# https://github.com/coreos/prometheus-operator/issues/1522
kubectl patch deployment kube-dns-v20 -n kube-system --patch "$(cat prom-graf-kube-dns-metrics-patch.yaml)"
```
My cluster running K8S v1.12.4 uses coredns, not kube-dns. I suggest an update to the step: first check if kube-dns is deployed, e.g. `kubectl get deploy -n kube-system`

**Comment by chzbrgr71** [comment]
This would be a great spot for a PR! 

AKS did recently switch to coredns. Good news that AKS is rapidly evolving, but unlikely that the hackfest will keep up.
